'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Editar

    '''<summary>
    '''lblAluno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAluno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAlunos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAlunos As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlEdicao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEdicao As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ucAlunoFormEditar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucAlunoFormEditar As Global.Escola.Web.AlunoForm

    '''<summary>
    '''btnSalvarAlteracoes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSalvarAlteracoes As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnApagarAluno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApagarAluno As Global.System.Web.UI.WebControls.Button
End Class
