'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AlterarSenha

    '''<summary>
    '''lblSucesso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSucesso As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSenhaAtual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSenhaAtual As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valSenhaAtualObrigatoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valSenhaAtualObrigatoria As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''valSenhaAtualCorreta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valSenhaAtualCorreta As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''txtNovaSenha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNovaSenha As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valNovaSenhaObrigatoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valNovaSenhaObrigatoria As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''valNovaSenhaFormato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valNovaSenhaFormato As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtNovaSenhaConfirmacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNovaSenhaConfirmacao As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valSenhasCoincidem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valSenhasCoincidem As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''btnEnviarAlteracao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEnviarAlteracao As Global.System.Web.UI.WebControls.Button
End Class
