'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default3

    '''<summary>
    '''lblSucesso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSucesso As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNomeDeUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomeDeUsuario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNomeDeUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeDeUsuario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valNomeDeUsuarioObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valNomeDeUsuarioObrigatorio As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''valNomeDeUsuarioFormato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valNomeDeUsuarioFormato As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''valNomeDeUsuarioExistente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valNomeDeUsuarioExistente As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''btnSalvarAlteracoes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSalvarAlteracoes As Global.System.Web.UI.WebControls.Button
End Class
