'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Registrar

    '''<summary>
    '''pnlFormUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFormUsuario As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblNomeDeUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomeDeUsuario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNomeDeUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeDeUsuario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valNomeDeUsuarioObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valNomeDeUsuarioObrigatorio As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''valNomeDeUsuarioFormato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valNomeDeUsuarioFormato As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''valNomeDeUsuarioExistente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valNomeDeUsuarioExistente As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''lblSenha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSenha As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSenha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSenha As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valSenhaObrigatoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valSenhaObrigatoria As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''valSenhaFormato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valSenhaFormato As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblConfirmarSenha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfirmarSenha As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtConfirmarSenha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConfirmarSenha As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valConfirmarSenhaObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valConfirmarSenhaObrigatorio As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''valConfirmarSenhaCoincide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valConfirmarSenhaCoincide As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''btnCriarConta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCriarConta As Global.System.Web.UI.WebControls.Button
End Class
